name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - run: yarn && yarn compile
